alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias tigs='tig status'
alias rb='rbenv'
alias be='bundle exec'
alias pt='pstree'
alias bi='bundle install --path=vendor/bundle --binstubs=.binstubs'
alias vless='/usr/local/opt/vim/share/vim/vim74/macros/less.sh'
alias u='j'
alias tailf='tail -f'
alias gtags='ctags -R --languages=-javascript --exclude=.git --exclude=log --exclude=target --fields=+iaS --extra=+q .'
alias mcopy='reattach-to-user-namespace pbcopy'
alias mpaste='reattach-to-user-namespace pbpaste'
alias ag='ack -H --smart-case --column --ignore-dir=.binstubs --ignore-dir=vendor --ignore-dir=log --ignore-dir=tmp --ignore-file=is:Session.vim --ignore-file=is:tags'
alias t='git ls-files | ack --smart-case --no-column --noenv'
alias vs='vim -S Session.vim'
gi() { gem install $@; rbenv rehash; rehash }
